Ecommerce/Areas/Admin/Controllers/BrandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Ecommerce.Areas.Admin.Models;
using Ecommerce.Data;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace Ecommerce.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class BrandController : Controller
    {
        private readonly CarContext _context;

        public BrandController(CarContext context)
        {
            _context = context;
        }
        public override void OnActionExecuted(ActionExecutedContext context)
        {
            ViewBag.listBrand = _context.brands.ToList();
            base.OnActionExecuted(context);
        }
        // GET: Admin/Brand
        public async Task<IActionResult> Index(int? id)
        {
            TempData["StatusMessage"] = "Create brand successfully";
            TempData["EditMessage"] = "Edit brand successfully";
            Brand brand = null;
            if (id != null)
            {
                brand = await _context.brands.FirstOrDefaultAsync(m => m.Id == id);
            }
            return View(brand);
        }

        // GET: Admin/Brand/Details/5
        //public async Task<IActionResult> Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var brand = await _context.brands
        //        .FirstOrDefaultAsync(m => m.Id == id);
        //    if (brand == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(brand);
        //}

        // GET: Admin/Brand/Create
        //public IActionResult Create()
        //{
        //    return View();
        //}

        // POST: Admin/Brand/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Status")] Brand brand ,IFormFile? ful)
            
        {
            var idd = _context.brands.Count() + 1;
            if (ModelState.IsValid)
            {
                if (ful != null)
                {
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/pro", idd + "." + ful.FileName.Split(".")[ful.FileName.Split(".").Length - 1]);
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await ful.CopyToAsync(stream);
                    }
                    
                    brand.Logo = idd + "." + ful.FileName.Split(".")[ful.FileName.Split(".").Length - 1];
                }
                else
                {
                    brand.Logo = "no-image.png";
                }
                
                _context.Add(brand);
               

                await _context.SaveChangesAsync();
                
                return RedirectToAction(nameof(Index));
            }
            return View("Index");
        }

       // GET: Admin/Brand/Edit/5
        //public async Task<IActionResult> Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var brand = await _context.brands.FindAsync(id);
        //    if (brand == null)
        //    {
        //        return NotFound();
        //    }
        //    return View(brand);
        //}

        // POST: Admin/Brand/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Logo,Status")] Brand brand,IFormFile ful)
        {
            if (id != brand.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (ful != null)
                    {
                        var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/pro", brand.Logo);
                        if (System.IO.File.Exists(path))
                        {
                            System.IO.File.Delete(path);
                        }
                        path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/pro", brand.Id + "." + ful.FileName.Split(".")[ful.FileName.Split(".").Length - 1]);
                        using (var stream = new FileStream(path, FileMode.Create))
                        {
                            await ful.CopyToAsync(stream);
                        }
                        brand.Logo = brand.Id + "." + ful.FileName.Split(".")[ful.FileName.Split(".").Length - 1];
                    }
     
                
                    _context.Update(brand);
                 
                    await _context.SaveChangesAsync();
                    
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BrandExists(brand.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            

            }
            return View("Index");
        }

        // GET: Admin/Brand/Delete/5
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var brand = await _context.brands
        //        .FirstOrDefaultAsync(m => m.Id == id);
        //    if (brand == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(brand);
        //}

        //// POST: Admin/Brand/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed(int id)
        //{
        //    var brand = await _context.brands.FindAsync(id);
        //    _context.brands.Remove(brand);
        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}

        private bool BrandExists(int id)
        {
            return _context.brands.Any(e => e.Id == id);
        }
    }
}

Ecommerce/Areas/Admin/Controllers/OderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Ecommerce.Areas.Admin.Models;
using Ecommerce.Data;

namespace Ecommerce.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class OderController : Controller
    {
        private readonly CarContext _context;

        public OderController(CarContext context)
        {
            _context = context;
        }

        // GET: Admin/Oder
        public async Task<IActionResult> Index()
        {
            var carContext = _context.oders.Include(o => o.User);
            return View(await carContext.ToListAsync());
        }

        // GET: Admin/Oder/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var oder = await _context.oders
                .Include(o => o.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (oder == null)
            {
                return NotFound();
            }

            return View(oder);
        }

        // GET: Admin/Oder/Create
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.users, "ID", "Address");
            return View();
        }

        // POST: Admin/Oder/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,OderDate,UserId,Status,TotalPrice")] Oder oder)
        {
            if (ModelState.IsValid)
            {
                _context.Add(oder);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.users, "ID", "Address", oder.UserId);
            return View(oder);
        }

        // GET: Admin/Oder/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var oder = await _context.oders.FindAsync(id);
            if (oder == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.users, "ID", "Address", oder.UserId);
            return View(oder);
        }

        // POST: Admin/Oder/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,OderDate,UserId,Status,TotalPrice")] Oder oder)
        {
            if (id != oder.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(oder);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OderExists(oder.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.users, "ID", "Address", oder.UserId);
            return View(oder);
        }

        // GET: Admin/Oder/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var oder = await _context.oders
                .Include(o => o.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (oder == null)
            {
                return NotFound();
            }

            return View(oder);
        }

        // POST: Admin/Oder/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var oder = await _context.oders.FindAsync(id);
            _context.oders.Remove(oder);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OderExists(int id)
        {
            return _context.oders.Any(e => e.Id == id);
        }
    }
}

Ecommerce/Areas/Admin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Ecommerce.Areas.Admin.Models;
using Ecommerce.Data;
using Microsoft.AspNetCore.Mvc.Filters;

namespace Ecommerce.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class UserController : Controller
    {
        private readonly CarContext _context;

        public UserController(CarContext context)
        {
            _context = context;
        }
        public override void OnActionExecuted(ActionExecutedContext context)
        {
            ViewBag.ListUser = _context.users.ToList();
            base.OnActionExecuted(context);
        }

        // GET: Admin/User
        public async Task<IActionResult> Index(int? id)
        {
            User user = null;
            if (id != null)
            {
                user = await _context.users.FirstOrDefaultAsync(m=>m.ID == id);

            }
            return View(user);
        }


        // POST: Admin/User/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,UserName,Password,Name,Address,Phone,Status,Gmail,Rule")] User user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View("Index");
        }
        // POST: Admin/User/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,UserName,Password,Name,Address,Phone,Status,Gmail,Rule")] User user)
        {
            if (id != user.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View("Index");
        }
        private bool UserExists(int id)
        {
            return _context.users.Any(e => e.ID == id);
        }
    }
}

Ecommerce/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ecommerce.Areas.Admin.Models;
using Ecommerce.Data;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Ecommerce.Controllers
{
    public class LoginController : Controller
    {
        private readonly CarContext _context;
        public LoginController(CarContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login([Bind("Gmail,Password")] User user)
        {
            var r = _context.users.Where(m => (m.Gmail == user.Gmail && m.Password ==
             /*StringProcessing.CreateMD5Hash(*/user.Password)).ToList() ;
            if (r.Count == 0)
            {
                return View("Index");
            }
            string str = r[0].Name;
            int tm = r[0].ID;
            HttpContext.Session.SetString("user", str);
            HttpContext.Session.SetInt32("userId", tm);
            if (r[0].Rule == 0)
            {
                var url = Url.RouteUrl("routeArea", new { Controller = "Home", action = "Index", area = "Admin" });
                return Redirect(url);
            }
            if (r[0].Rule == 1)
            {
                int userRule = r[0].Rule;
                HttpContext.Session.SetString("userrule", userRule.ToString());
                return RedirectToAction("index", "DynamicPages");
            }
            return RedirectToAction("index", "DynamicPages");

        }
        public IActionResult Logout()
        {
            if(HttpContext.Session.GetString("userrule") == "1")
            {
                HttpContext.Session.Remove("user");
                HttpContext.Session.Remove("userrule");
                var url = Url.RouteUrl("dafault", new { Controller = "DynamicPages", action = "Index"});
                return Redirect(url);
            }
            HttpContext.Session.Remove("user");
            HttpContext.Session.Remove("userrule");
            return RedirectToAction("index", "login");

        }
    }
}

Ecommerce/Areas/Admin/Views/Shared/_HeadPartial.cshtml
<title> Home :: Admin</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Pooled Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- Bootstrap Core CSS -->
<link href="~/Admin/css/bootstrap.min.css" rel='stylesheet' type='text/css' />
<!-- Custom CSS -->
<link href="~/Admin/css/style.css?@{new Random().Next(1, 1000).ToString();}" rel='stylesheet' type='text/css' />
<link rel="stylesheet" href="~/Admin/css/morris.css" type="text/css" />
<!-- Graph CSS -->
<link href="~/Admin/css/font-awesome.css" rel="stylesheet">
<!-- jQuery -->
<script src="~/Admin/js/jquery-2.1.4.min.js"></script>
<!-- //jQuery -->
<link href='//fonts.googleapis.com/css?family=Roboto:700,500,300,100italic,100,400' rel='stylesheet' type='text/css' />
<link href='//fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
<!-- lined-icons -->
<link rel="stylesheet" href="~/Admin/css/icon-font.min.css" type='text/css' />
<!-- //lined-icons -->

Ecommerce/Areas/Admin/Views/Shared/_HeaderMainPartial.cshtml
<div class="header-main">

    <div class="profile_details w3l">
        <ul>
            <li class="dropdown profile_details_drop">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <div class="profile_img">
                        <span class="prfil-img"><img src="images/in4.jpg" alt=""> </span>
                        <div class="user-name">
                            <p>Malorum</p>
                            <span>Administrator</span>
                        </div>
                        <i class="fa fa-angle-down"></i>
                        <i class="fa fa-angle-up"></i>
                        <div class="clearfix"></div>
                    </div>
                </a>
                <ul class="dropdown-menu drp-mnu">
                    <li> <a href="#"><i class="fa fa-cog"></i> Settings</a> </li>
                    <li> <a href="#"><i class="fa fa-user"></i> Profile</a> </li>
                    <li> <a asp-area="" asp-action="Logout" asp-controller="Login"><i class="fa fa-sign-out"></i> Logout</a> </li>
                </ul>
            </li>
        </ul>
    </div>

    <div class="clearfix"> </div>
</div>

Ecommerce/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @await Html.PartialAsync("_HeadPartial")
</head>
<body>
    <div class="page-container">
        <div class="left-content">
            <div class="mother-grid-inner">
                @await Html.PartialAsync("_HeaderMainPartial")
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html">Home</a> <i class="fa fa-angle-right"></i></li>
                </ol>
                <div>
                    @RenderBody()
                </div>
            </div>
        </div>
        @await Html.PartialAsync("_SidebarPartial")
        <div class="clearfix"></div>
    </div>
    <!--copy rights start here-->
    <div class="copyrights">
        <p>© All Rights Reserved | Design by  <a href="http://w3layouts.com/" target="_blank">Cong</a> </p>
    </div>
    <!--COPY rights end here-->
    @await Html.PartialAsync("_ValidationScriptsPartial")
    @RenderSection("Scripts", false)
</body>
</html>

Ecommerce/Areas/Admin/Views/Shared/_SidebarPartial.cshtml
			<!--/sidebar-menu-->
<div class="sidebar-menu">
    <header class="logo1">
        <a href="#" class="sidebar-icon"> <span class="fa fa-bars"></span>  </a>
    </header>
    <div style="border-top:1px ridge rgba(255, 255, 255, 0.15)"></div>
    <div class="menu">
        <ul id="menu">
            <li><a asp-controller="Home" asp-action="Index"><i aria-hidden="true"></i><span>Home</span> <span style="float: right"></span><div class="clearfix"></div></a></li>

            <li id="menu-academico">
                <a asp-controller="Brand" asp-action="Index"><i aria-hidden="true"></i><span>Brand</span> <span style="float: right"></span><div class="clearfix"></div></a>
            </li>
            <li id="menu-academico">
                <a asp-controller="Categorie" asp-action="Index"><i aria-hidden="true"></i><span>Categorie</span> <span style="float: right"></span><div class="clearfix"></div></a>
            </li>
            <li id="menu-academico">
                <a asp-controller="Oder" asp-action="Index"><i aria-hidden="true"></i><span>Oder</span> <span style="float: right"></span><div class="clearfix"></div></a>
            </li>
            <li id="menu-academico">
                <a asp-controller="OderDetail" asp-action="Index"><i aria-hidden="true"></i><span>OderDetail</span> <span style="float: right"></span><div class="clearfix"></div></a>
            </li>
            <li id="menu-academico">
                <a asp-controller="Product" asp-action="Index"><i aria-hidden="true"></i><span>Product</span> <span style="float: right"></span><div class="clearfix"></div></a>
            </li>
          
            <li id="menu-academico">
                <a asp-controller="User" asp-action="Index"><i aria-hidden="true"></i><span>Account</span> <span style="float: right"></span><div class="clearfix"></div></a>
            </li>
        </ul>
    </div>
</div>

@**@